POST http://localhost:5000/login
Content-Type: application/json

{
    "name":"bangjago",
    "password":"rahasia"
}

###
POST http://localhost:5000/movies/favourite
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibmFtZSI6ImJhbmdqYWdvIiwicGFzc3dvcmQiOiIkMmIkMTAkSHRINHFudERGTnpuNkxYODM3d0lYZXJQYndJazZDOGZsUHVGV2VjcDl6Ykx2cFVxNkFBSXEiLCJjcmVhdGVkQXQiOm51bGwsInVwZGF0ZWRBdCI6bnVsbCwiaWF0IjoxNjIzNDA5NTQwLCJleHAiOjE2MjM0MDk2MDB9.Bbr6P5IbivlwlYMC9i_b3KlOxagZo04KY2yYdnnPYrg

{
    "title":"6 hari di guoa"
}

###
GET http://localhost:5000/movies/g-force
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibmFtZSI6ImJhbmdqYWdvIiwicGFzc3dvcmQiOiIkMmIkMTAkSHRINHFudERGTnpuNkxYODM3d0lYZXJQYndJazZDOGZsUHVGV2VjcDl6Ykx2cFVxNkFBSXEiLCJjcmVhdGVkQXQiOm51bGwsInVwZGF0ZWRBdCI6bnVsbCwiaWF0IjoxNjIzNDExMjAwLCJleHAiOjE2MjM0MTEyNjB9.-YpDnNGcdAZxrwcbtt9RdJw7rzla1JTR13g6IFzBOFA
###
GET http://localhost:5000/movies/favourite
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibmFtZSI6ImJhbmdqYWdvIiwicGFzc3dvcmQiOiIkMmIkMTAkSHRINHFudERGTnpuNkxYODM3d0lYZXJQYndJazZDOGZsUHVGV2VjcDl6Ykx2cFVxNkFBSXEiLCJjcmVhdGVkQXQiOm51bGwsInVwZGF0ZWRBdCI6bnVsbCwiaWF0IjoxNjIzNDExMzI5fQ.fikgwZ1H-zbBFEcJ1oR9flSQQNrtrjj6bJihrnW1iDo